# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe36248d4fa2fb54d1290050753725f1c8458794741c45cd34dee9f5f3a605795f7fa0ba677a8a9539cbb369fef5eeca27c9ac54f25b5689c6cf512b8874286

test:
  secret_key_base: 2b19e75f2961c56740b3d7f7a029061cde5217945a50f344224f5183006b7c54996dd5617b3a7e3565273630fc2ec923d6ce7cb657b72e5b3d1b93f7f05eb456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
